name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Download Go modules
      run: go mod download

    - name: Build for Linux
      run: CGO_ENABLED=0 GOOS=linux go build -o splitter-linux cmd/splitter/main.go

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: splitter-linux
        path: splitter-linux

    - name: Build for Windows
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o splitter-windows.exe cmd/splitter/main.go

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: splitter-windows
        path: splitter-windows.exe
